package com.jamk.thesis.modules;
// Generated by Qodo Gen

import com.jamk.thesis.modules.Account;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;


public class AccountTest {


    // Create account with valid parameters and verify properties
    @Test
    public void test_create_account_with_valid_parameters() {
        String accountNumber = "123456789";
        String owner = "John Doe";
        double initialBalance = 1000.0;
    
        Account account = new Account(accountNumber, owner, initialBalance);
    
        assertEquals(accountNumber, account.getAccountNumber());
        assertEquals(owner, account.getOwner());
        assertEquals(initialBalance, account.getBalance(), 0.001);
    }

    // Deposit positive amount and check balance increases correctly
    @Test
    public void test_deposit_positive_amount() {
        Account account = new Account("123456789", "John Doe", 1000.0);
        double depositAmount = 500.0;
        double initialBalance = account.getBalance();
    
        account.deposit(depositAmount);
    
        assertEquals(initialBalance + depositAmount, account.getBalance(), 0.001);
    }

    // Withdraw valid amount and verify balance decreases correctly
    @Test
    public void test_withdraw_valid_amount() {
        Account account = new Account("123456789", "John Doe", 1000.0);
        double withdrawAmount = 500.0;
        double initialBalance = account.getBalance();
    
        account.withdraw(withdrawAmount);
    
        assertEquals(initialBalance - withdrawAmount, account.getBalance(), 0.001);
    }

    // Set balance to new value and verify it updates correctly
    @Test
    public void test_set_balance_updates_correctly() {
        Account account = new Account("123456789", "John Doe", 1000.0);
        double newBalance = 2500.0;
    
        account.setBalance(newBalance);
    
        assertEquals(newBalance, account.getBalance(), 0.001);
    }

    // Get account number returns correct value
    @Test
    public void test_get_account_number() {
        String expectedAccountNumber = "987654321";
        Account account = new Account(expectedAccountNumber, "Jane Doe", 500.0);
    
        String actualAccountNumber = account.getAccountNumber();
    
        assertEquals(expectedAccountNumber, actualAccountNumber);
    }

    // Create account with negative initial balance throws IllegalArgumentException
    @Test
    public void test_create_account_with_negative_balance() {
        String accountNumber = "123456789";
        String owner = "John Doe";
        double negativeBalance = -100.0;
    
        IllegalArgumentException exception = assertThrows(
            IllegalArgumentException.class,
            () -> new Account(accountNumber, owner, negativeBalance)
        );
    
        assertEquals("Initial balance cannot be negative.", exception.getMessage());
    }

    // Deposit zero or negative amount throws IllegalArgumentException
    @Test
    public void test_deposit_non_positive_amount() {
        Account account = new Account("123456789", "John Doe", 1000.0);
    
        IllegalArgumentException zeroException = assertThrows(
            IllegalArgumentException.class,
            () -> account.deposit(0.0)
        );
    
        IllegalArgumentException negativeException = assertThrows(
            IllegalArgumentException.class,
            () -> account.deposit(-50.0)
        );
    
        assertEquals("Deposit amount must be positive.", zeroException.getMessage());
        assertEquals("Deposit amount must be positive.", negativeException.getMessage());
    }

    // Withdraw zero or negative amount throws IllegalArgumentException
    @Test
    public void test_withdraw_non_positive_amount() {
        Account account = new Account("123456789", "John Doe", 1000.0);
    
        IllegalArgumentException zeroException = assertThrows(
            IllegalArgumentException.class,
            () -> account.withdraw(0.0)
        );
    
        IllegalArgumentException negativeException = assertThrows(
            IllegalArgumentException.class,
            () -> account.withdraw(-50.0)
        );
    
        assertEquals("Withdrawal amount must be positive.", zeroException.getMessage());
        assertEquals("Withdrawal amount must be positive.", negativeException.getMessage());
    }

    // Withdraw amount greater than balance throws IllegalArgumentException
    @Test
    public void test_withdraw_amount_greater_than_balance() {
        Account account = new Account("123456789", "John Doe", 100.0);
        double excessiveAmount = 150.0;
    
        IllegalArgumentException exception = assertThrows(
            IllegalArgumentException.class,
            () -> account.withdraw(excessiveAmount)
        );
    
        assertEquals("Insufficient balance.", exception.getMessage());
    }

    // Create account with zero initial balance is valid
    @Test
    public void test_create_account_with_zero_balance() {
        String accountNumber = "123456789";
        String owner = "John Doe";
        double initialBalance = 0.0;
    
        Account account = new Account(accountNumber, owner, initialBalance);
    
        assertEquals(accountNumber, account.getAccountNumber());
        assertEquals(owner, account.getOwner());
        assertEquals(initialBalance, account.getBalance(), 0.001);
    }
}