package com.jamk.thesis.modules;
// Generated by Qodo Gen

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;


public class BankTest {


    // Adding an account to the bank
    @Test
    public void test_add_account_to_bank() {
        // Arrange
        Bank bank = new Bank();
        Account account = new Account("123456", "John Doe", 1000.0);
    
        // Act
        bank.addAccount(account);
    
        // Assert
        Account retrievedAccount = bank.getAccount("123456");
        assertEquals(account, retrievedAccount);
        assertEquals(1000.0, bank.getTotalBalance());
    }

    @Test
    public void test_exception_message_for_duplicate_account() {
        Bank bank = new Bank();
        Account account1 = new Account("123456", "John Doe", 1000.0);
        Account account2 = new Account("123456", "Jane Smith", 2000.0);

        bank.addAccount(account1);

        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            bank.addAccount(account2);
        });

        assertEquals("Account already exists.", exception.getMessage());
    }

    // Getting an account with a non-existent account number returns null
    @Test
    public void test_get_non_existent_account_returns_null() {
        // Arrange
        Bank bank = new Bank();
        bank.addAccount(new Account("123456", "John Doe", 1000.0));
    
        // Act
        Account nonExistentAccount = bank.getAccount("999999");
    
        // Assert
        assertNull(nonExistentAccount);
    }

    // Calculating total balance across all accounts
    @Test
    public void test_total_balance_calculation() {
        // Arrange
        Bank bank = new Bank();
        Account account1 = new Account("123456", "John Doe", 1000.0);
        Account account2 = new Account("789012", "Jane Smith", 2000.0);
        bank.addAccount(account1);
        bank.addAccount(account2);

        // Act
        double totalBalance = bank.getTotalBalance();

        // Assert
        assertEquals(3000.0, totalBalance);
    }

    // Getting an account by account number when it exists
    @Test
    public void test_get_account_by_account_number() {
        // Arrange
        Bank bank = new Bank();
        Account account = new Account("123456", "John Doe", 1000.0);
        bank.addAccount(account);

        // Act
        Account retrievedAccount = bank.getAccount("123456");

        // Assert
        assertNotNull(retrievedAccount);
        assertEquals("123456", retrievedAccount.getAccountNumber());
        assertEquals("John Doe", retrievedAccount.getOwner());
        assertEquals(1000.0, retrievedAccount.getBalance());
    }

    // Transferring money between two valid accounts
    @Test
    public void test_transfer_between_valid_accounts() throws Exception {
        // Arrange
        Bank bank = new Bank();
        Account account1 = new Account("123456", "John Doe", 1000.0);
        Account account2 = new Account("654321", "Jane Smith", 500.0);
        bank.addAccount(account1);
        bank.addAccount(account2);

        // Act
        boolean result = bank.transfer("123456", "654321", 200.0);

        // Assert
        assertTrue(result);
        assertEquals(800.0, account1.getBalance());
        assertEquals(700.0, account2.getBalance());
    }

    @Test
    public void test_transfer_with_nonexistent_source_account() {
        Bank bank = new Bank();
        Account destAccount = new Account("67890", "Jane Smith", 500.0);
        bank.addAccount(destAccount);

        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            bank.transfer("12345", "67890", 100.0);
        });

        assertEquals("Invalid account number(s).", exception.getMessage());
        assertEquals(500.0, destAccount.getBalance());
    }

    // Executing a successful transaction using TransactionAction
    @Test
    public void test_execute_transaction_success() throws Exception {
        // Arrange
        Bank bank = new Bank();
        Account account1 = new Account("123456", "John Doe", 1000.0);
        Account account2 = new Account("654321", "Jane Doe", 500.0);
        bank.addAccount(account1);
        bank.addAccount(account2);
    
        // Act
        bank.executeTransaction(() -> {
            account1.withdraw(200.0);
            account2.deposit(200.0);
        });
    
        // Assert
        assertEquals(800.0, account1.getBalance());
        assertEquals(700.0, account2.getBalance());
    }

    // Creating and restoring snapshots of account balances
    @Test
    public void test_transaction_rollback_on_failure() throws Exception {
        // Arrange
        Bank bank = new Bank();
        Account account1 = new Account("123456", "John Doe", 1000.0);
        Account account2 = new Account("654321", "Jane Doe", 500.0);
        bank.addAccount(account1);
        bank.addAccount(account2);

        // Act
        try {
            bank.transfer("123456", "654321", 1500.0);
        } catch (Exception e) {
            // Expected exception due to insufficient funds
        }

        // Assert
        assertEquals(1000.0, account1.getBalance());
        assertEquals(500.0, account2.getBalance());
    }

    // Transferring money with invalid account numbers throws IllegalArgumentException
    @Test
    public void test_transfer_with_invalid_account_numbers() {
        // Arrange
        Bank bank = new Bank();
        Account account1 = new Account("123456", "John Doe", 1000.0);
        bank.addAccount(account1);

        // Act & Assert
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            bank.transfer("123456", "654321", 100.0);
        });

        assertEquals("Invalid account number(s).", exception.getMessage());
    }

    // Transferring more money than available in source account causes rollback
    @Test
    public void test_transfer_exceeds_balance_causes_rollback() {
        // Arrange
        Bank bank = new Bank();
        Account sourceAccount = new Account("123456", "John Doe", 500.0);
        Account destinationAccount = new Account("654321", "Jane Doe", 300.0);
        bank.addAccount(sourceAccount);
        bank.addAccount(destinationAccount);

        // Act & Assert
        Exception exception = assertThrows(Exception.class, () -> {
            bank.transfer("123456", "654321", 600.0);
        });

        // Assert
        assertEquals("Insufficient balance.", exception.getMessage());
        assertEquals(500.0, sourceAccount.getBalance());
        assertEquals(300.0, destinationAccount.getBalance());
    }

    // Executing a transaction that throws an exception causes rollback
    @Test
    public void test_transaction_rollback_on_exception() {
        // Arrange
        Bank bank = new Bank();
        Account account1 = new Account("123456", "John Doe", 1000.0);
        Account account2 = new Account("654321", "Jane Doe", 500.0);
        bank.addAccount(account1);
        bank.addAccount(account2);

        double initialBalance1 = account1.getBalance();
        double initialBalance2 = account2.getBalance();

        // Act & Assert
        assertThrows(Exception.class, () -> {
            bank.executeTransaction(() -> {
                account1.withdraw(200.0);
                account2.deposit(200.0);
                throw new Exception("Simulated transaction failure");
            });
        });

        // Assert rollback
        assertEquals(initialBalance1, account1.getBalance());
        assertEquals(initialBalance2, account2.getBalance());
    }

    // Bank initialization with empty accounts list
    @Test
    public void test_bank_initialization_with_empty_accounts() {
        // Arrange & Act
        Bank bank = new Bank();

        // Assert
        assertEquals(0, bank.getTotalBalance());
        assertNull(bank.getAccount("nonexistent"));
    }

    // Transferring zero or negative amounts between accounts
    @Test
    public void test_transfer_zero_or_negative_amount() {
        // Arrange
        Bank bank = new Bank();
        Account account1 = new Account("123456", "John Doe", 1000.0);
        Account account2 = new Account("654321", "Jane Doe", 500.0);
        bank.addAccount(account1);
        bank.addAccount(account2);

        // Act & Assert
        Exception exceptionZero = assertThrows(IllegalArgumentException.class, () -> {
            bank.transfer("123456", "654321", 0);
        });
        assertEquals("Withdrawal amount must be positive.", exceptionZero.getMessage());

        Exception exceptionNegative = assertThrows(IllegalArgumentException.class, () -> {
            bank.transfer("123456", "654321", -100);
        });
        assertEquals("Withdrawal amount must be positive.", exceptionNegative.getMessage());

        // Ensure balances remain unchanged
        assertEquals(1000.0, account1.getBalance());
        assertEquals(500.0, account2.getBalance());
    }

    // Performance with large number of accounts
    @Test
    public void test_performance_with_large_number_of_accounts() {
        // Arrange
        Bank bank = new Bank();
        int numberOfAccounts = 100000;
        double initialBalance = 100.0;
        for (int i = 0; i < numberOfAccounts; i++) {
            Account account = new Account(String.valueOf(i), "Owner" + i, initialBalance);
            bank.addAccount(account);
        }

        // Act
        double totalBalance = bank.getTotalBalance();

        // Assert
        assertEquals(numberOfAccounts * initialBalance, totalBalance);
    }

    // Concurrent access to bank operations
    @Test
    public void test_concurrent_transfers() throws InterruptedException {
        // Arrange
        Bank bank = new Bank();
        Account account1 = new Account("123456", "John Doe", 1000.0);
        Account account2 = new Account("654321", "Jane Doe", 1000.0);
        bank.addAccount(account1);
        bank.addAccount(account2);

        // Act
        Thread thread1 = new Thread(() -> {
            try {
                bank.transfer("123456", "654321", 100.0);
            } catch (Exception e) {
                e.printStackTrace();
            }
        });

        Thread thread2 = new Thread(() -> {
            try {
                bank.transfer("654321", "123456", 200.0);
            } catch (Exception e) {
                e.printStackTrace();
            }
        });

        thread1.start();
        thread2.start();

        thread1.join();
        thread2.join();

        // Assert
        assertEquals(2000.0, account1.getBalance() + account2.getBalance());
    }

    // Transaction isolation between multiple transfers
    @Test
    public void test_transaction_isolation_between_multiple_transfers() throws Exception {
        // Arrange
        Bank bank = new Bank();
        Account account1 = new Account("123456", "John Doe", 1000.0);
        Account account2 = new Account("654321", "Jane Doe", 500.0);
        Account account3 = new Account("111111", "Jim Beam", 300.0);
        bank.addAccount(account1);
        bank.addAccount(account2);
        bank.addAccount(account3);

        // Act & Assert
        assertTrue(bank.transfer("123456", "654321", 200.0));
        assertEquals(800.0, account1.getBalance());
        assertEquals(700.0, account2.getBalance());

        assertTrue(bank.transfer("654321", "111111", 100.0));
        assertEquals(600.0, account2.getBalance());
        assertEquals(400.0, account3.getBalance());

        // Ensure isolation: previous transfers should not affect this one
        assertTrue(bank.transfer("123456", "111111", 300.0));
        assertEquals(500.0, account1.getBalance());
        assertEquals(700.0, account3.getBalance());
    }

    // Handling of decimal precision in balance calculations
    @Test
    public void test_decimal_precision_in_balance_calculations() {
        // Arrange
        Bank bank = new Bank();
        Account account1 = new Account("123456", "John Doe", 1000.123);
        Account account2 = new Account("654321", "Jane Doe", 2000.456);
        bank.addAccount(account1);
        bank.addAccount(account2);

        // Act
        double totalBalance = bank.getTotalBalance();

        // Assert
        assertEquals(3000.579, totalBalance, 0.001);
    }
}