package com.jamk.thesis.modules;
// Generated by Qodo Gen

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class CalculatorTest {


    // Basic arithmetic operations (add, subtract, multiply) return correct results for positive integers
    @Test
    public void test_basic_arithmetic_operations_with_positive_integers() {
        Calculator calculator = new Calculator();
    
        // Test addition
        assertEquals(5, calculator.add(2, 3));
        assertEquals(10, calculator.add(7, 3));
    
        // Test subtraction
        assertEquals(4, calculator.subtract(7, 3));
        assertEquals(1, calculator.subtract(5, 4));
    
        // Test multiplication
        assertEquals(6, calculator.multiply(2, 3));
        assertEquals(20, calculator.multiply(4, 5));
    }

    // Division by zero throws IllegalArgumentException
    @Test
    public void test_division_by_zero_throws_exception() {
        Calculator calculator = new Calculator();
    
        IllegalArgumentException exception = assertThrows(
            IllegalArgumentException.class,
            () -> calculator.divide(10, 0)
        );
    
        assertEquals("Divider cannot be zero.", exception.getMessage());
    }

    // Division returns correct floating-point result for valid inputs
    @Test
    public void test_division_with_valid_inputs() {
        Calculator calculator = new Calculator();

        // Test division
        assertEquals(2.5, calculator.divide(5, 2), 0.0001);
        assertEquals(3.0, calculator.divide(9, 3), 0.0001);
        assertEquals(1.3333, calculator.divide(4, 3), 0.0001);
    }

    // Fibonacci returns correct sequence values for valid indices
    @Test
    public void test_fibonacci_sequence_values() {
        Calculator calculator = new Calculator();

        // Test Fibonacci sequence
        assertEquals(0, calculator.fibonacci(0));
        assertEquals(1, calculator.fibonacci(1));
        assertEquals(1, calculator.fibonacci(2));
        assertEquals(2, calculator.fibonacci(3));
        assertEquals(3, calculator.fibonacci(4));
        assertEquals(5, calculator.fibonacci(5));
        assertEquals(8, calculator.fibonacci(6));
    }

    // Factorial returns correct results for small positive integers
    @Test
    public void test_factorial_with_small_positive_integers() {
        Calculator calculator = new Calculator();

        assertEquals(1, calculator.factorial(0));
        assertEquals(1, calculator.factorial(1));
        assertEquals(2, calculator.factorial(2));
        assertEquals(6, calculator.factorial(3));
        assertEquals(24, calculator.factorial(4));
        assertEquals(120, calculator.factorial(5));
    }

    // Logarithm returns correct value for valid inputs
    @Test
    public void test_logarithm_with_valid_inputs() {
        Calculator calculator = new Calculator();
    
        // Test logarithm with base 10
        assertEquals(2.0, calculator.logarithm(100, 10), 0.0001);
    
        // Test natural logarithm (base e)
        assertEquals(1.0, calculator.logarithm(Math.E, Math.E), 0.0001);
    
        // Test logarithm with base 2
        assertEquals(3.0, calculator.logarithm(8, 2), 0.0001);
    }

    // Power function correctly calculates base raised to exponent
    @Test
    public void test_power_function_with_various_bases_and_exponents() {
        Calculator calculator = new Calculator();
    
        // Test power with positive base and exponent
        assertEquals(8.0, calculator.power(2, 3), 0.0001);
    
        // Test power with negative base and positive exponent
        assertEquals(-8.0, calculator.power(-2, 3), 0.0001);
    
        // Test power with positive base and zero exponent
        assertEquals(1.0, calculator.power(5, 0), 0.0001);
    
        // Test power with zero base and positive exponent
        assertEquals(0.0, calculator.power(0, 5), 0.0001);
    
        // Test power with zero base and zero exponent (conventionally 1)
        assertEquals(1.0, calculator.power(0, 0), 0.0001);
    
        // Test power with negative base and even exponent
        assertEquals(16.0, calculator.power(-2, 4), 0.0001);
    }

    // GCD correctly finds greatest common divisor for positive integers
    @Test
    public void test_gcd_with_positive_integers() {
        Calculator calculator = new Calculator();

        // Test GCD
        assertEquals(6, calculator.gcd(54, 24));
        assertEquals(1, calculator.gcd(17, 13));
        assertEquals(5, calculator.gcd(10, 5));
        assertEquals(12, calculator.gcd(36, 60));
    }

    // Factorial with negative input throws IllegalArgumentException
    @Test
    public void test_factorial_with_negative_input_throws_exception() {
        Calculator calculator = new Calculator();
        assertThrows(IllegalArgumentException.class, () -> {
            calculator.factorial(-1);
        });
    }

    // Trigonometric functions return expected values for common angles
    @Test
    public void test_trigonometric_functions_for_common_angles() {
        Calculator calculator = new Calculator();
    
        // Test sin function
        assertEquals(0, calculator.sin(0), 1e-9);
        assertEquals(1, calculator.sin(Math.PI / 2), 1e-9);
        assertEquals(0, calculator.sin(Math.PI), 1e-9);
    
        // Test cos function
        assertEquals(1, calculator.cos(0), 1e-9);
        assertEquals(0, calculator.cos(Math.PI / 2), 1e-9);
        assertEquals(-1, calculator.cos(Math.PI), 1e-9);
    
        // Test tan function
        assertEquals(0, calculator.tan(0), 1e-9);
        assertEquals(1, calculator.tan(Math.PI / 4), 1e-9);
    }

    // Permutation and combination functions return correct values for valid inputs
    @Test
    public void test_permutation_and_combination_with_valid_inputs() {
        Calculator calculator = new Calculator();

        // Test permutation
        assertEquals(6, calculator.permutation(3, 2));
        assertEquals(20, calculator.permutation(5, 2));

        // Test combination
        assertEquals(3, calculator.combination(3, 2));
        assertEquals(10, calculator.combination(5, 2));
    }

    // LCM correctly calculates least common multiple for positive integers
    @Test
    public void test_lcm_with_positive_integers() {
        Calculator calculator = new Calculator();

        // Test LCM
        assertEquals(12, calculator.lcm(4, 6));
        assertEquals(15, calculator.lcm(3, 5));
        assertEquals(35, calculator.lcm(5, 7));
        assertEquals(60, calculator.lcm(12, 15));
    }

    @Test
    public void test_lcm_with_both_parameters_zero() {
        Calculator calculator = new Calculator();
        int result = calculator.lcm(0, 0);
        assertEquals(0, result);
    }

    @Test
    public void test_lcm_with_one_parameter_zero() {
        Calculator calculator = new Calculator();
        int result = calculator.lcm(0, 5);
        assertEquals(0, result);

        result = calculator.lcm(7, 0);
        assertEquals(0, result);
    }

    // Fibonacci with negative index throws IllegalArgumentException
    @Test
    public void test_fibonacci_with_negative_index_throws_exception() {
        Calculator calculator = new Calculator();
    
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            calculator.fibonacci(-1);
        });
    
        assertEquals("Negative index not allowed.", exception.getMessage());
    }

    // Logarithm with base=1 throws IllegalArgumentException
    @Test
    public void test_logarithm_with_base_one_throws_exception() {
        Calculator calculator = new Calculator();
        assertThrows(IllegalArgumentException.class, () -> {
            calculator.logarithm(10, 1);
        });
    }

    // Quadratic solver returns correct roots for equations with real solutions
    @Test
    public void test_quadratic_solver_with_real_roots() {
        Calculator calculator = new Calculator();
    
        // Test case with two distinct real roots
        double[] roots1 = calculator.solveQuadratic(1, -3, 2);
        assertEquals(2, roots1.length);
        assertEquals(2.0, roots1[0], 0.0001);
        assertEquals(1.0, roots1[1], 0.0001);
    
        // Test case with one real root (double root)
        double[] roots2 = calculator.solveQuadratic(1, -2, 1);
        assertEquals(1, roots2.length);
        assertEquals(1.0, roots2[0], 0.0001);
    }

    // Quadratic solver with a=0 throws IllegalArgumentException
    @Test
    public void test_quadratic_solver_with_a_zero_throws_exception() {
        Calculator calculator = new Calculator();
        assertThrows(IllegalArgumentException.class, () -> {
            calculator.solveQuadratic(0, 2, 3);
        });
    }

    // Logarithm with non-positive value or base throws IllegalArgumentException
    @Test
    public void test_logarithm_with_non_positive_value_or_base_throws_exception() {
        Calculator calculator = new Calculator();
    
        // Test with non-positive value
        assertThrows(IllegalArgumentException.class, () -> calculator.logarithm(0, 2));
        assertThrows(IllegalArgumentException.class, () -> calculator.logarithm(-1, 2));
    
        // Test with non-positive base
        assertThrows(IllegalArgumentException.class, () -> calculator.logarithm(2, 0));
        assertThrows(IllegalArgumentException.class, () -> calculator.logarithm(2, -1));
    
        // Test with base equal to 1
        assertThrows(IllegalArgumentException.class, () -> calculator.logarithm(2, 1));
    }

    // Quadratic solver returns empty array for equations with no real roots
    @Test
    public void test_quadratic_solver_no_real_roots() {
        Calculator calculator = new Calculator();
    
        double[] roots = calculator.solveQuadratic(1, 0, 1);
    
        assertEquals(0, roots.length);
    }

    // Polynomial derivative of constant returns array with single zero
    @Test
    public void test_polynomial_derivative_of_constant() {
        Calculator calculator = new Calculator();

        double[] coefficients = {5.0}; // Constant polynomial
        double[] expectedDerivative = {0.0};

        assertArrayEquals(expectedDerivative, calculator.polynomialDerivative(coefficients));
    }

    @Test
    public void test_linear_polynomial_derivative() {
        Calculator calculator = new Calculator();
        double[] coefficients = {2, 3};
        double[] expected = {2};
        double[] result = calculator.polynomialDerivative(coefficients);
        assertArrayEquals(expected, result, 0.0001);
    }

    @Test
    public void test_null_coefficients_array() {
        Calculator calculator = new Calculator();
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            calculator.polynomialDerivative(null);
        });
        assertEquals("Coefficient array is empty.", exception.getMessage());
    }

    @Test
    public void test_empty_coefficients_array() {
        double[] coefficients = {};

        Calculator calculator = new Calculator();

        IllegalArgumentException exception = assertThrows(
                IllegalArgumentException.class,
                () -> calculator.polynomialDerivative(coefficients)
        );

        assertEquals("Coefficient array is empty.", exception.getMessage());
    }

    // Permutation and combination with invalid inputs throw IllegalArgumentException
    @Test
    public void test_permutation_and_combination_with_invalid_inputs() {
        Calculator calculator = new Calculator();

        // Test invalid inputs for permutation
        assertThrows(IllegalArgumentException.class, () -> calculator.permutation(-1, 2));
        assertThrows(IllegalArgumentException.class, () -> calculator.permutation(5, -1));
        assertThrows(IllegalArgumentException.class, () -> calculator.permutation(3, 4));

        // Test invalid inputs for combination
        assertThrows(IllegalArgumentException.class, () -> calculator.combination(-1, 2));
        assertThrows(IllegalArgumentException.class, () -> calculator.combination(5, -1));
        assertThrows(IllegalArgumentException.class, () -> calculator.combination(3, 4));
    }
}