package com.jamk.thesis.modules;
// Generated by Qodo Gen

import org.junit.jupiter.api.Test;


import java.util.*;

import static org.junit.jupiter.api.Assertions.*;


public class GraphUtilTest {


    // hasCycle correctly identifies a graph with a cycle
    @Test
    public void test_has_cycle_identifies_graph_with_cycle() {
        // Create a graph with a cycle: 1 -> 2 -> 3 -> 1
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(2));
        graph.put(2, Arrays.asList(3));
        graph.put(3, Arrays.asList(1));
    
        boolean result = GraphUtil.hasCycle(graph);
    
        assertTrue(result, "Graph with cycle should be identified correctly");
    }

    // Empty graph handling in all methods
    @Test
    public void test_empty_graph_handling_in_all_methods() {
        // Create an empty graph
        Map<Integer, List<Integer>> emptyGraph = new HashMap<>();
    
        // Test hasCycle with empty graph
        assertFalse(GraphUtil.hasCycle(emptyGraph), "Empty graph should not have a cycle");
    
        // Test topologicalSort with empty graph
        List<Integer> topologicalOrder = GraphUtil.topologicalSort(emptyGraph);
        assertTrue(topologicalOrder.isEmpty(), "Topological sort of empty graph should be empty");
    
        // Test isBipartite with empty graph
        assertTrue(GraphUtil.isBipartite(emptyGraph), "Empty graph should be bipartite");
    
        // Test shortestPath with empty graph
        List<Integer> path = GraphUtil.shortestPath(emptyGraph, 1, 2);
        assertTrue(path.isEmpty(), "Shortest path in empty graph should be empty");
    }

    // isBipartite correctly identifies a bipartite graph
    @Test
    public void test_is_bipartite_identifies_bipartite_graph() {
        // Create a bipartite graph: 1 -- 2, 3 -- 4
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(2));
        graph.put(2, Arrays.asList(1, 3));
        graph.put(3, Arrays.asList(2, 4));
        graph.put(4, Arrays.asList(3));

        boolean result = GraphUtil.isBipartite(graph);

        assertTrue(result, "Graph should be identified as bipartite");
    }

    // hasCycle correctly identifies a graph without a cycle
    @Test
    public void test_has_cycle_identifies_graph_without_cycle() {
        // Create a graph without a cycle: 1 -> 2, 2 -> 3
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(2));
        graph.put(2, Arrays.asList(3));
        graph.put(3, new ArrayList<>());

        boolean result = GraphUtil.hasCycle(graph);

        assertFalse(result, "Graph without cycle should be identified correctly");
    }

    // isBipartite correctly identifies a non-bipartite graph
    @Test
    public void test_is_bipartite_identifies_non_bipartite_graph() {
        // Create a non-bipartite graph: 1 -- 2 -- 3 -- 1 (triangle)
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(2, 3));
        graph.put(2, Arrays.asList(1, 3));
        graph.put(3, Arrays.asList(1, 2));

        boolean result = GraphUtil.isBipartite(graph);

        assertFalse(result, "Graph with an odd-length cycle should not be bipartite");
    }

    // shortestPath returns the correct path between two connected nodes
    @Test
    public void test_shortest_path_between_connected_nodes() {
        // Create a graph with a path: 1 -> 2 -> 3
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(2));
        graph.put(2, Arrays.asList(3));
        graph.put(3, new ArrayList<>());

        List<Integer> expectedPath = Arrays.asList(1, 2, 3);
        List<Integer> result = GraphUtil.shortestPath(graph, 1, 3);

        assertEquals(expectedPath, result, "The shortest path between connected nodes should be correct");
    }

    // Graph with disconnected components in topologicalSort
    @Test
    public void test_topological_sort_with_disconnected_components() {
        // Create a graph with disconnected components: 1 -> 2, 3 -> 4
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(2));
        graph.put(2, new ArrayList<>());
        graph.put(3, Arrays.asList(4));
        graph.put(4, new ArrayList<>());

        List<Integer> result = GraphUtil.topologicalSort(graph);

        // The result can be [1, 2, 3, 4] or [3, 4, 1, 2] or any order that respects the dependencies
        assertTrue(result.indexOf(1) < result.indexOf(2), "Node 1 should come before Node 2");
        assertTrue(result.indexOf(3) < result.indexOf(4), "Node 3 should come before Node 4");
    }

    // Graph with self-loops in hasCycle
    @Test
    public void test_has_cycle_identifies_graph_with_self_loop() {
        // Create a graph with a self-loop: 1 -> 1
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(1));

        boolean result = GraphUtil.hasCycle(graph);

        assertTrue(result, "Graph with self-loop should be identified as having a cycle");
    }

    // Single node graph in isBipartite
    @Test
    public void test_is_bipartite_single_node_graph() {
        // Create a single node graph: 1
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, new ArrayList<>());

        boolean result = GraphUtil.isBipartite(graph);

        assertTrue(result, "Single node graph should be bipartite");
    }

    // Graph with isolated nodes (no edges)
    @Test
    public void test_has_cycle_with_isolated_nodes() {
        // Create a graph with isolated nodes: 1, 2, 3
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Collections.emptyList());
        graph.put(2, Collections.emptyList());
        graph.put(3, Collections.emptyList());

        boolean result = GraphUtil.hasCycle(graph);

        assertFalse(result, "Graph with isolated nodes should not have a cycle");
    }

    // Graph with cycles in topologicalSort (should throw IllegalArgumentException)
    @Test
    public void test_topological_sort_throws_exception_on_cyclic_graph() {
        // Create a graph with a cycle: 1 -> 2 -> 3 -> 1
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(2));
        graph.put(2, Arrays.asList(3));
        graph.put(3, Arrays.asList(1));

        assertThrows(IllegalArgumentException.class, () -> {
            GraphUtil.topologicalSort(graph);
        }, "Graph with cycle should throw IllegalArgumentException");
    }

    // Start node equals end node in shortestPath
    @Test
    public void test_shortest_path_start_equals_end() {
        // Create a graph with some nodes and edges
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(2, 3));
        graph.put(2, Arrays.asList(3));
        graph.put(3, Arrays.asList(4));
        graph.put(4, Arrays.asList());

        // Test when start node equals end node
        List<Integer> result = GraphUtil.shortestPath(graph, 2, 2);

        // Verify the result is a list containing only the start/end node
        assertEquals(Arrays.asList(2), result, "Path should contain only the start/end node when they are the same");
    }

    // No path exists between nodes in shortestPath
    @Test
    public void test_shortest_path_no_path_exists() {
        // Create a graph where no path exists between node 1 and node 4
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(2));
        graph.put(2, Arrays.asList(3));
        graph.put(3, Arrays.asList());
        graph.put(4, Arrays.asList(5));
        graph.put(5, Arrays.asList());

        List<Integer> result = GraphUtil.shortestPath(graph, 1, 4);

        assertTrue(result.isEmpty(), "No path should exist between node 1 and node 4");
    }

    // topologicalSort returns nodes in correct topological order for a DAG
    @Test
    public void test_topological_sort_correct_order_for_dag() {
        // Create a DAG: 5 -> 11, 7 -> 11, 7 -> 8, 3 -> 8, 3 -> 10, 11 -> 2, 11 -> 9, 8 -> 9
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(5, Arrays.asList(11));
        graph.put(7, Arrays.asList(11, 8));
        graph.put(3, Arrays.asList(8, 10));
        graph.put(11, Arrays.asList(2, 9));
        graph.put(8, Arrays.asList(9));
        graph.put(2, new ArrayList<>());
        graph.put(9, new ArrayList<>());
        graph.put(10, new ArrayList<>());
    
        List<Integer> result = GraphUtil.topologicalSort(graph);
    
        // Verify the topological order
        assertTrue(result.indexOf(5) < result.indexOf(11), "5 should come before 11");
        assertTrue(result.indexOf(7) < result.indexOf(11), "7 should come before 11");
        assertTrue(result.indexOf(7) < result.indexOf(8), "7 should come before 8");
        assertTrue(result.indexOf(3) < result.indexOf(8), "3 should come before 8");
        assertTrue(result.indexOf(3) < result.indexOf(10), "3 should come before 10");
        assertTrue(result.indexOf(11) < result.indexOf(2), "11 should come before 2");
        assertTrue(result.indexOf(11) < result.indexOf(9), "11 should come before 9");
        assertTrue(result.indexOf(8) < result.indexOf(9), "8 should come before 9");
    }

    // Null input handling
    @Test
    public void test_null_input_handling() {
        assertThrows(NullPointerException.class, () -> {
            GraphUtil.hasCycle(null);
        }, "Null input should throw NullPointerException for hasCycle");

        assertThrows(NullPointerException.class, () -> {
            GraphUtil.topologicalSort(null);
        }, "Null input should throw NullPointerException for topologicalSort");

        assertThrows(NullPointerException.class, () -> {
            GraphUtil.isBipartite(null);
        }, "Null input should throw NullPointerException for isBipartite");

        assertThrows(NullPointerException.class, () -> {
            GraphUtil.shortestPath(null, 0, 1);
        }, "Null input should throw NullPointerException for shortestPath");
    }

    // Graphs where all nodes form a single cycle
    @Test
    public void test_has_cycle_identifies_single_cycle_graph() {
        // Create a graph where all nodes form a single cycle: 1 -> 2 -> 3 -> 4 -> 1
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(2));
        graph.put(2, Arrays.asList(3));
        graph.put(3, Arrays.asList(4));
        graph.put(4, Arrays.asList(1));

        boolean result = GraphUtil.hasCycle(graph);

        assertTrue(result, "Graph where all nodes form a single cycle should be identified correctly");
    }

    // All methods handle normal connected graphs correctly
    @Test
    public void test_all_methods_handle_connected_graphs() {
        // Create a connected graph: 1 -> 2 -> 3, 2 -> 4
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(2));
        graph.put(2, Arrays.asList(3, 4));
        graph.put(3, new ArrayList<>());
        graph.put(4, new ArrayList<>());

        // Test hasCycle method
        boolean hasCycleResult = GraphUtil.hasCycle(graph);
        assertFalse(hasCycleResult, "Connected graph without cycle should not be identified as having a cycle");

        // Test topologicalSort method
        List<Integer> topologicalSortResult = GraphUtil.topologicalSort(graph);
        assertEquals(Arrays.asList(1, 2, 4, 3), topologicalSortResult, "Topological sort should return correct order");

        // Test isBipartite method
        boolean isBipartiteResult = GraphUtil.isBipartite(graph);
        assertTrue(isBipartiteResult, "Connected bipartite graph should be identified correctly");

        // Test shortestPath method
        List<Integer> shortestPathResult = GraphUtil.shortestPath(graph, 1, 4);
        assertEquals(Arrays.asList(1, 2, 4), shortestPathResult, "Shortest path should be identified correctly");
    }

    // Large graphs with many nodes and edges
    @Test
    public void test_large_graph_performance() {
        // Create a large graph with 1000 nodes and 2000 edges
        Map<Integer, List<Integer>> graph = new HashMap<>();
        for (int i = 0; i < 1000; i++) {
            graph.put(i, new ArrayList<>());
        }
        for (int i = 0; i < 2000; i++) {
            int from = (int) (Math.random() * 1000);
            int to = (int) (Math.random() * 1000);
            graph.get(from).add(to);
        }
    
        // Test if the graph has a cycle
        boolean hasCycle = GraphUtil.hasCycle(graph);
    
        // Test topological sort on the graph
        try {
            List<Integer> sortedList = GraphUtil.topologicalSort(graph);
            assertNotNull(sortedList, "Topological sort should return a non-null list");
        } catch (IllegalArgumentException e) {
            assertTrue(hasCycle, "Exception should be thrown only if the graph has a cycle");
        }
    
        // Test if the graph is bipartite
        boolean isBipartite = GraphUtil.isBipartite(graph);
    
        // Test shortest path between two random nodes
        int start = (int) (Math.random() * 1000);
        int end = (int) (Math.random() * 1000);
        List<Integer> path = GraphUtil.shortestPath(graph, start, end);
    
        assertNotNull(path, "Shortest path should return a non-null list");
    }

    // Graphs with multiple valid topological orderings
    @Test
    public void test_topological_sort_multiple_valid_orderings() {
        // Create a graph with multiple valid topological orderings: 1 -> 2, 1 -> 3
        Map<Integer, List<Integer>> graph = new HashMap<>();
        graph.put(1, Arrays.asList(2, 3));
        graph.put(2, new ArrayList<>());
        graph.put(3, new ArrayList<>());

        List<Integer> result = GraphUtil.topologicalSort(graph);

        // Check that the result is a valid topological ordering
        assertTrue(result.indexOf(1) < result.indexOf(2), "Node 1 should come before Node 2");
        assertTrue(result.indexOf(1) < result.indexOf(3), "Node 1 should come before Node 3");
    }

    // Complex bipartite graphs with multiple disconnected components
    @Test
    public void test_is_bipartite_with_disconnected_components() {
        // Create a complex bipartite graph with multiple disconnected components
        Map<Integer, List<Integer>> graph = new HashMap<>();
        // Component 1: Bipartite (0 - 1)
        graph.put(0, Arrays.asList(1));
        graph.put(1, Arrays.asList(0));
        // Component 2: Bipartite (2 - 3 - 4)
        graph.put(2, Arrays.asList(3));
        graph.put(3, Arrays.asList(2, 4));
        graph.put(4, Arrays.asList(3));
        // Component 3: Single node (5)
        graph.put(5, new ArrayList<>());
    
        boolean result = GraphUtil.isBipartite(graph);
    
        assertTrue(result, "Graph with multiple disconnected bipartite components should be identified as bipartite");
    }
}